version: '3'
services:
  postgresql:
    image: postgres:16
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "keycloak", "-d", "keycloak"]
      interval: 1s
      timeout: 2s
      retries: 300
    env_file:
      - env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/databases/keycloak:/var/lib/postgresql/data/pgdata

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    command: ["start"]
    env_file:
      - env
    # Uncomment and set your values if using our nginx proxy example
    # environment:
    # - VIRTUAL_HOST=https://id.example.org # used by nginx proxy 
    # - VIRTUAL_PORT=8080 # used by nginx proxy
    # - LETSENCRYPT_HOST=https://id.example.org # used by lets encrypt to generate TLS certificate
    depends_on:
      kc_postgresql:
        condition: service_healthy
        restart: true