services:
  kc_postgresql:
    image: postgres:16
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "keycloak", "-d", "keycloak"]
      interval: 1s
      timeout: 2s
      retries: 300
    env_file:
      - env.d/kc_postgresql
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/databases/keycloak:/var/lib/postgresql/data/pgdata

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    command: ["start"]
      # ports:
      # - 8080
    env_file:
      - env.d/keycloak
      - env.d/kc_postgresql
    depends_on:
      kc_postgresql:
        condition: service_healthy
        restart: true