---
services:
  minio-bootstrap:
    image: minio/mc
    env_file:
    - env.d/production/minio
    depends_on:
      minio:
        condition: service_healthy
        restart: true
    entrypoint: >
      sh -c " /usr/bin/mc alias set docs http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}
      && \ /usr/bin/mc mb --ignore-existing docs/docs-media-storage && \ /usr/bin/mc
      version enable docs/docs-media-storage && \ exit 0;"

  minio:
    user: ${DOCKER_USER:-1000}
    image: minio/minio
    env_file:
    - env.d/production/minio
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 1s
      timeout: 20s
      retries: 300
    entrypoint: ""
    command: minio server /data
    volumes:
    - ./data/production/media:/data
